spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/ai_legal_assistant
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug